# Generated by Django 4.2.16 on 2025-03-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('resident', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tutorial_session', models.TextField(max_length=250)),
                ('accomodation', models.TextField(max_length=250)),
                ('disability', models.TextField(max_length=250)),
                ('certificate', models.TextField(max_length=250)),
                ('marital', models.CharField(max_length=200)),
                ('passport_size', models.ImageField(upload_to='application_passports/')),
                ('certificates', models.FileField(upload_to='application_certificates/')),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.programs')),
            ],
        ),
    ]
