# Generated by Django 4.2.16 on 2025-03-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageToForm',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
