# Generated by Django 4.1.5 on 2023-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageToForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_date", models.DateField()),
            ],
        ),
    ]
