# Generated by Django 4.2.16 on 2025-03-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0002_delete_messagetoform_delete_registration'),
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Herroes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
