# Generated by Django 4.2.16 on 2025-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_remove_profile_is_landlord_profile_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
